import dotenv from "dotenv";
import axios from "axios";
import FormData from "form-data";
import fs from "fs";

dotenv.config();

//Function for sending message from template
async function sendTemplateMessage(){
    const response = await axios({
        url: "https://graph.facebook.com/v20.0/878498734984/messages",
        method: "post",
        headers: {
            "Authorization": `Bearer ${process.env.WHATSAPP_TOKEN}`,
            "Content-Type": "application/json"
        },
        data: JSON.stringify({
            messaging_product: "whatsapp",
            to: "copy from API Setup (To) copy from curl code",
            type: "template",
            template: {
                name: "template-name",
                language: {
                    code: "en_US"
                }
            },
        })
    })
    console.log(response.data)
}


//Function for sending message from custom template
async function sendTemplateMessage(){
    const response = await axios({
        url: "https://graph.facebook.com/v20.0/878498734984/messages",
        method: "post",
        headers: {
            "Authorization": `Bearer ${process.env.WHATSAPP_TOKEN}`,
            "Content-Type": "application/json"
        },
        data: JSON.stringify({
            messaging_product: "whatsapp",
            to: "copy from API Setup (To) copy from curl code",
            type: "template",
            template: {
                name: "discount",
                language: {
                    code: "en_US"
                },
                components: {                 //For variables
                    type: "header",
                    parameters: [
                        {
                            type: "text",      //Variables for header
                            text: "Shivam Swaroop"
                        }
                    ]
                },
                {
                    type: "body",
                    parameters: [
                        {
                            type: "text",      //Variables for body
                            text: "50"
                        }
                    ]
                }
            },
        })
    })
    console.log(response.data)
}

//Function for sending message from text but user send message first
async function sendTextMessage(){
    const response = await axios({
        url: "https://graph.facebook.com/v20.0/878498734984/messages",
        method: "post",
        headers: {
            "Authorization": `Bearer ${process.env.WHATSAPP_TOKEN}`,
            "Content-Type": "application/json"
        },
        data: JSON.stringify({
            messaging_product: "whatsapp",
            to: "copy from API Setup (To) copy from curl code",
            type: "text",
            text: {
                body: "This is the text message from Whatsapp API",
            },
        })
    })
    console.log(response.data)
}


//Function for sending media
async function sendMediaMessage(){
    const response = await axios({
        url: "https://graph.facebook.com/v20.0/878498734984/messages",
        method: "post",
        headers: {
            "Authorization": `Bearer ${process.env.WHATSAPP_TOKEN}`,
            "Content-Type": "application/json"
        },
        data: JSON.stringify({
            messaging_product: "whatsapp",
            to: "copy from API Setup (To) copy from curl code",
            type: "image",
            image: {
                link: "image_url.png",
                // id: "868737656735765",  //For sending image from server using id and id generated by uploadImage function
                caption: "This is caption for image"
            },
        })
    })
    console.log(response.data)
}


//Function for upload image from app server
async function uploadImage(){
    const data = new FormData()
    data.append("messaging_product", "whatsapp")
    data.append("file", fs.createReadStream(process.cwd() + "/logo.png"), {contentType: "image/png"})
    data.append("type", "image/png")

    const response = await axios({
        url: "https://graph.facebook.com/v20.0/878498734984/media",
        method: "post",
        headers: {
            "Authorization": `Bearer ${process.env.WHATSAPP_TOKEN}`,
        },
        data: data
    })
    console.log(response.data)
}

sendTemplateMessage()
sendTextMessage()
sendMediaMessage()